export const Data=[
    {
        id:0,
        title:'Courses',
        category:[
            {
                name:'programming',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            },{
                name:'design',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            },
            {
                name:'marketing',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            }
        ],
       
    },  
    {
        id:1,
        title:'Exam & exercise',
        category:[
            {
                name:'programming2',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            },{
                name:'design2',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            },
            {
                name:'marketing2',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            }
        ]
        
    },
    {
        id:2,
        title:'Webinar',
        category:[
            {
                name:'programming3',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            },{
                name:'design3',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            },
            {
                name:'marketing3',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            }
        ]
            
    },
    {
        id:3,
        title:'Subject',
        category:[
            {
                name:'programming4',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            },{
                name:'design4',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            },
            {
                name:'marketing4',
                course:[
                    {
                       topic:'HTML', 
                    },
                    {
                        topic:'CSS', 
                     },
                     {
                        topic:'JAVA', 
                     },
                     {
                        topic:'Python', 
                     },
                     {
                        topic:'SQL', 
                     },

                ]
            }
        ]
    },
]
